### ISSUE TITLE
Play modules respository

### ISSUE THREAD

**Issue by hypexr** [maklemenz/minifymod#9]
Hi,

Is there a reason minifymod is not included in the play module repository?

Thanks

**Comment by maklemenz** [comment]
Hi,

at the time of writing this module the official module repository was closed and no new modules were accepted. Maybe to push play2 or nobody who had the permissions cared.
I don't think somebody will add play1 modules today, since they are ignored since 2012: [registration request](https://groups.google.com/forum/#!searchin/play-framework/minifymod/play-framework/x3SNGni4ZkA/oAsEfmvBa0gJ)

Are you using this modules or planning to use it?

**Comment by hypexr** [comment]
Ahh, that makes sense. I started using it last week and just added it as a local module in dependencies.yml. 

Thanks!
